### PR TITLE
Diego thermodynamic fix

### PR DESCRIPTION
**Pull request by diegomartinez2**
The fix for the Thermodynamic error inside "Ensemble.py".

### CODE REVIEW

**Comment by diegomartinez2** [comment]
Failed the aiida test with "ValueError: required pseudo family `SSSP/1.3/PBEsol/efficiency` is not installed. Please use `aiida-pseudo install` toinstall it."

**Comment by mesonepigreco** [comment]
Hi, this is strange,
I am rerunning an old job to see if it was working the AiiDA part, or if it is another error introduced by an updated from the AiiDA people.

**Comment by diegomartinez2** [comment]
Yep, it also failed in the old code. Something changed in the AiiDa.

**Comment by mesonepigreco** [comment]
True, let me try to fix it on the master workflow, so you can pull that into this branch and then merge

**Comment by diegomartinez2** [comment]
Taken out the AiiDa second test it compiles OK.

**Comment by mesonepigreco** [comment]
Ok, I would avoid removing the test, @bastonero is looking into it right now ;)
If you undo the last commit I merge even if it does not pass, otherwise, when @bastonero fixes the test we will have a merge conflict.

**Comment by diegomartinez2** [comment]
Last commit undone.

**Comment by bastonero** [comment]
Just opened the PR! (:

**Review by mesonepigreco — APPROVED** [review]
The changes have been discussed throught the issues and the pull request comments.
This pull request fix the dependency issue of spglib and the module Thermodynamics compilation issue with numpy distutils.

**Pull request merged**
